### ISSUE TITLE
passport-http abandoned?

### ISSUE THREAD

**Issue by nickcmaynard** [jaredhanson/passport-http#40]
18 months since @jaredhanson committed or merged pull requests.  Should we fork to integrate fixes?  Does anyone want to volunteer to do this?

**Comment by bgSosh** [comment]
Would be great to get the project live again.  I'm not able to though unfortunately.

**Comment by mren** [comment]
@jaredhanson Any feedback on the projects status? A short answer how you want to proceed would be great.

**Comment by jaredhanson** [comment]
I'm going to be picking up the slack on Passport-related projects over the next couple of weeks.

**Comment by mren** [comment]
Awesome, thanks for the fast feedback. I'm looking forward.

**Comment by jeremykentbgross** [comment]
Just FYI: The project doesn't work for me out of the box at all.  I cannot even require it.  I have tried all manner of ways, but:

```
require('passport-http');
```

returns:

```
{}
```

And most of the example ways I find to require it on the web tell me that the package cannot be found at all.  I tried messing around in the package myself, but I couldn't get it to return anything other than the empty object.  My node version is 0.10.26, although they have the new stable 0.12.0 out as of about a week ago.

Would be sweet if it was fixed since I am trying to use it for a project.

In the mean time is there another version someone is keeping up to date?

**Comment by jeremykentbgross** [comment]
Update: correction, it returns:

{
	"version": "0.2.2"
}

On my last post I had been fiddling with the code inside the node_modules folder to try to get it to work.  Any chance this will be fixed in the near future?

**Comment by nickcmaynard** [comment]
@jaredhanson What are you planning to do here? I wonder if someone could deputise for you? I don't have the bandwidth to help, sadly...

**Comment by wbruno** [comment]
any news? @jaredhanson

**Comment by jaredhanson** [comment]
Closing. Bump any outstanding issues you'd like to see addressed.
